### ISSUE TITLE
세이브시 멈춤현상

### ISSUE THREAD

**Issue by Wintiger0222** [koipkoi/pokecrystal-kr#4]
![cap 2019-01-03 10-12-27-262](https://user-images.githubusercontent.com/24960466/50620235-b2e2a700-0f41-11e9-8684-3ea43cbe100b.png)
세이브 도중 멈춤 현상이 발생합니다.
세이브 문제는 아니고 메뉴타일 백업루틴으로 인해
글자수 초과로 멈추는것 같습니다.

참고로 debug모드 관련 루틴 빼고 전부 하드카피했습니다.

**Comment by koipkoi** [comment]
@Wintiger0222 제 프로젝트에서는 아무 문제 없습니다.
혹시나 해서 코드 수정사항을 반영하지 않으신게 있을까봐 아래처럼 시도해봤습니다.

메뉴 백업 관련해서 한글 고유번호 저장 부분에서 문제가 발견되어서
engine/korean/text_korean.asm 180행 TrimTable 루틴을 수정했었는데

1)
ld c, wKoreanTextTableBufferEnd - wKoreanTextTableBuffer을
ld c, (wKoreanTextTableBufferEnd - wKoreanTextTableBuffer) / 2으로

2) 180행에 inc hl 추가

위 변경 사항을 다시 예전 것으로 고치고 테스트해보니 같은 현상이 발생했습니다.
결론은 TrimTable 변경사항을 적용하지 않으신것 같네요

**Comment by Wintiger0222** [comment]
181행에 inc hl 추가된거 확인하지 못했습니다. 죄송합니다.
